import type { ExpoConfig } from 'expo/config';

/**
 * Expo app configuration.
 *
 * TypeScript rather than `app.json` for one reason: the API base URL has to be
 * read from the environment at build time and defaulted for local development,
 * which static JSON cannot do. Nothing secret is read here — `EXPO_PUBLIC_*`
 * values are compiled into the bundle and are public by definition
 * (docs/mobile/security.md), so the only variable is the base URL.
 *
 * The built APK (or exported bundle) is checked for accidental secrets by
 * `npm run scan:apk <file>` (ST-60) at the repo root.
 */

/**
 * `localhost` is the *device's* own loopback, so it never reaches a laptop.
 * The default therefore stays the Android emulator alias for the host machine
 * (10.0.2.2); a physical phone needs the LAN address passed explicitly:
 *
 *   EXPO_PUBLIC_API_URL=http://192.168.1.20:4000/api/v1 npx expo start
 */
const DEFAULT_API_URL = 'http://10.0.2.2:4000/api/v1';

const apiUrl = process.env.EXPO_PUBLIC_API_URL ?? DEFAULT_API_URL;

const config: ExpoConfig = {
  name: 'Khetri',
  slug: 'him-1096-khetri',
  scheme: 'khetri',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'light',
  // The design is a single light theme on purpose: the stated field context is
  // bright sunlight (web/frontend/src/index.css carries the same note).
  backgroundColor: '#f6f8f6',
  primaryColor: '#277249',
  assetBundlePatterns: ['**/*'],
  android: {
    package: 'in.him1096.khetri',
    versionCode: 1,
    adaptiveIcon: {
      backgroundColor: '#dcf0e1',
      foregroundImage: './assets/android-icon-foreground.png',
      backgroundImage: './assets/android-icon-background.png',
      monochromeImage: './assets/android-icon-monochrome.png',
    },
    // Every one of these is requested in context with a localized rationale,
    // and every feature degrades when it is denied (docs/mobile/security.md).
    // RECORD_AUDIO is absent: the shipped voice feature is TTS-out only
    // (docs/voice/voice-interface.md — the intents-only path).
    permissions: ['android.permission.CAMERA', 'android.permission.ACCESS_FINE_LOCATION'],
    blockedPermissions: ['android.permission.RECORD_AUDIO'],
    predictiveBackGestureEnabled: false,
  },
  /**
   * No `locales` block. docs/mobile/i18n.md called for one to localize the
   * OS-level permission strings, but Expo's `locales` compiles to iOS
   * `InfoPlist.strings` only — Android's permission sheet text is generated by
   * the system and cannot be overridden by an app. Android is the only shipped
   * target (docs/mobile/deployment.md), so the block would have been inert.
   * The rationale the farmer actually reads is our own in-context screen,
   * localized through `shared/i18n` like everything else.
   */
  extra: {
    apiUrl,
    /**
     * The EAS link, and ONLY when one exists.
     *
     * An earlier version wrote `projectId: process.env.EAS_PROJECT_ID ?? null`,
     * which looks harmless and is not: Expo's config normalisation turns that
     * `null` into `{}`, so `extra.eas.projectId` resolved to an *object*, and
     * tooling that expects a string id got one. Omitting the key entirely is
     * the honest representation of "this project is not linked yet" —
     * `eas init` adds it.
     */
    ...(process.env.EAS_PROJECT_ID ? { eas: { projectId: process.env.EAS_PROJECT_ID } } : {}),
  },
  plugins: [
    'expo-secure-store',
    'expo-localization',
    [
      'expo-camera',
      {
        cameraPermission: 'Khetri uses the camera to photograph your crop leaves.',
        /**
         * The plugin adds `RECORD_AUDIO` by default so video capture can carry
         * sound. This app photographs leaves and never records, so the
         * permission is declined at source rather than merely blocked
         * afterwards — an app that asks for a microphone it never uses is a
         * permission a farmer is right to refuse.
         */
        recordAudioAndroid: false,
      },
    ],
    [
      'expo-image-picker',
      {
        photosPermission: 'Khetri opens your gallery so you can pick a photo of your crop.',
      },
    ],
    [
      'expo-location',
      {
        locationAlwaysAndWhenInUsePermission:
          'Khetri uses your location once, to place your farm on the map. You can type the district instead.',
      },
    ],
  ],
};

export default config;
