/**
 * The viewfinder.
 *
 * Full-bleed and header-less because the frame *is* the interface: the single
 * biggest determinant of whether the chain can name a lesion is whether the
 * leaf fills the frame, and every pixel spent on chrome is a pixel the farmer
 * cannot aim with.
 *
 * ## Permission is a screen, not a dialog
 *
 * Android's own permission sheet is generated by the system and cannot be
 * localized by an app (see the note in app.config.ts), so the sentence that
 * actually explains *why* has to be ours, shown before the sheet appears
 * (docs/mobile/security.md — "requested in context with a localized
 * rationale"). Four outcomes each get a designed screen rather than a dead end:
 *
 *  - not yet asked  → the rationale, with an explicit Allow;
 *  - refused once   → the same rationale, re-askable;
 *  - refused for good (`canAskAgain === false`) → a route into system settings;
 *  - no camera at all (`onMountError`) → the gallery.
 *
 * Every one of those also offers the gallery, because a farmer whose camera we
 * cannot open still has yesterday's photograph of the same leaf.
 */
import { useRef, useState } from 'react';
import { Image, Linking, Pressable, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import { useIsFocused } from '@react-navigation/native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Screen } from '../../components/ui/Screen';
import { SectionHeader } from '../../components/ui/SectionHeader';
import { Switch } from '../../components/ui/Switch';
import { ErrorState, LoadingState } from '../../components/ui/states';
import { IconCamera, IconChevronLeft, IconUpload } from '../../components/ui/icons';
import { Text } from '../../components/ui/Text';
import { PRESSED_OPACITY, TOUCH_TARGET, colors, radius, spacing } from '../../theme';
import type { ScanStackParamList } from '../../navigation/types';

type Props = NativeStackScreenProps<ScanStackParamList, 'Camera'>;

/**
 * The server's own ceiling, from `MAX_HEALTH_DESCRIPTION` in
 * `backend/src/config/constants.js`. The analyze schema is `.strict()`, so a
 * longer note is a 400 rather than a truncation — the field stops accepting
 * characters here instead of letting the farmer lose a finished sentence.
 */
const MAX_DESCRIPTION = 500;

/** The photo the farmer is looking at, before they commit to sending it. */
interface Draft {
  uri: string;
}

export function CameraScreen({ navigation, route }: Props) {
  const { cropId } = route.params;
  const { t } = useTranslation(['mobile', 'health', 'common', 'errors']);
  const isFocused = useIsFocused();

  const [permission, requestPermission] = useCameraPermissions();
  const cameraRef = useRef<CameraView | null>(null);

  const [ready, setReady] = useState(false);
  const [mountFailed, setMountFailed] = useState(false);
  const [capturing, setCapturing] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [description, setDescription] = useState('');
  const [shareToCommunity, setShareToCommunity] = useState(false);
  const [pickerError, setPickerError] = useState(false);

  const openGallery = async () => {
    setPickerError(false);
    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ['images'],
        allowsMultipleSelection: false,
        // Full quality out of the picker; `services/image.ts` owns the one
        // re-encode, so compressing twice would only cost detail.
        quality: 1,
        exif: false,
      });

      const asset = result.canceled ? undefined : result.assets[0];
      if (asset) setDraft({ uri: asset.uri });
    } catch {
      setPickerError(true);
    }
  };

  const capture = async () => {
    if (!cameraRef.current || !ready || capturing) return;

    setCapturing(true);
    try {
      const photo = await cameraRef.current.takePictureAsync({
        quality: 1,
        exif: false,
        // Orientation correction stays on: a leaf photographed sideways is a
        // leaf the model sees sideways.
        skipProcessing: false,
      });
      if (photo?.uri) setDraft({ uri: photo.uri });
    } catch {
      setMountFailed(true);
    } finally {
      setCapturing(false);
    }
  };

  // ── Preview: the last chance to reject a blurred frame ────────────────────
  if (draft) {
    const note = description.trim();

    return (
      <Screen
        scroll
        keyboardAvoiding
        edges={['top', 'left', 'right', 'bottom']}
        testID="camera-preview"
      >
        <SectionHeader title={t('mobile:camera.guidanceTitle')} />

        <View style={styles.previewFrame} accessible accessibilityLabel={t('health:photoAlt')}>
          <Image source={{ uri: draft.uri }} style={styles.previewFill} resizeMode="cover" />
        </View>

        {/*
          The one thing a photograph cannot carry — how long it has been going
          on, what the farmer noticed first. The AI tier is given it as context;
          it never becomes advice on its own (rule 6), so the field is genuinely
          optional and says so in its label.
        */}
        <Card>
          <Input
            label={t('health:descriptionLabel')}
            placeholder={t('health:descriptionPlaceholder')}
            value={description}
            onChangeText={setDescription}
            multiline
            maxLength={MAX_DESCRIPTION}
            testID="camera-description"
          />
        </Card>

        <Card>
          <Switch
            label={t('health:shareLabel')}
            hint={t('health:shareHint')}
            value={shareToCommunity}
            onValueChange={setShareToCommunity}
            testID="camera-share"
          />
        </Card>

        <Button
          size="lg"
          fullWidth
          leadingIcon={<IconUpload size={22} color={colors.surface} />}
          onPress={() =>
            navigation.replace('Analyzing', {
              cropId,
              imageUri: draft.uri,
              shareToCommunity,
              // Omitted rather than sent empty: the server stores what it is
              // given, and a blank note is not something the farmer wrote.
              ...(note ? { description: note } : {}),
            })
          }
          testID="camera-use-photo"
        >
          {t('mobile:camera.usePhoto')}
        </Button>

        <Button variant="secondary" fullWidth onPress={() => setDraft(null)}>
          {t('mobile:camera.retake')}
        </Button>
      </Screen>
    );
  }

  // ── Permission has not been resolved yet ──────────────────────────────────
  if (!permission) {
    return (
      <Screen testID="camera-permission-loading">
        <LoadingState label={t('mobile:camera.starting')} />
      </Screen>
    );
  }

  // ── Permission refused ────────────────────────────────────────────────────
  if (!permission.granted) {
    const permanent = !permission.canAskAgain;

    return (
      <Screen testID="camera-permission">
        <SectionHeader
          title={
            permanent
              ? t('mobile:permission.cameraDeniedTitle')
              : t('mobile:permission.cameraTitle')
          }
          description={
            permanent ? t('mobile:permission.cameraDeniedBody') : t('mobile:permission.cameraBody')
          }
        />

        {permanent ? (
          <Button
            size="lg"
            fullWidth
            onPress={() => void Linking.openSettings()}
            testID="camera-open-settings"
          >
            {t('mobile:permission.openSettings')}
          </Button>
        ) : (
          <Button
            size="lg"
            fullWidth
            leadingIcon={<IconCamera size={22} color={colors.surface} />}
            onPress={() => void requestPermission()}
            testID="camera-request-permission"
          >
            {t('mobile:permission.cameraCta')}
          </Button>
        )}

        <GalleryFallback onPress={() => void openGallery()} failed={pickerError} />
      </Screen>
    );
  }

  // ── The device has no usable camera ───────────────────────────────────────
  if (mountFailed) {
    return (
      <Screen testID="camera-unavailable">
        <SectionHeader
          title={t('mobile:camera.unavailableTitle')}
          description={t('mobile:camera.unavailableBody')}
        />
        <GalleryFallback onPress={() => void openGallery()} failed={pickerError} />
        <Button variant="ghost" fullWidth onPress={() => navigation.goBack()}>
          {t('common:action.back')}
        </Button>
      </Screen>
    );
  }

  // ── The viewfinder ────────────────────────────────────────────────────────
  return (
    <View style={styles.fill} testID="camera-view">
      <CameraView
        ref={cameraRef}
        style={styles.fill}
        facing="back"
        // Released while the farmer is on another tab: an open camera is one of
        // the few things in this app that drains a battery measurably.
        active={isFocused}
        onCameraReady={() => setReady(true)}
        onMountError={() => setMountFailed(true)}
      />

      <SafeAreaView style={styles.overlay} pointerEvents="box-none">
        <View style={styles.topBar} pointerEvents="box-none">
          <Pressable
            onPress={() => navigation.goBack()}
            accessibilityRole="button"
            accessibilityLabel={t('common:action.back')}
            style={({ pressed }) => [styles.iconButton, pressed && { opacity: PRESSED_OPACITY }]}
          >
            <IconChevronLeft size={26} color={colors.surface} />
          </Pressable>

          <View style={styles.guidance}>
            <Text variant="bodyStrong" color="inverse">
              {t('mobile:camera.guidanceTitle')}
            </Text>
            <Text variant="caption" color="inverse">
              {t('mobile:camera.guidanceHint')}
            </Text>
          </View>
        </View>

        {/*
          The framing rectangle. Decorative — the spoken guidance is the text
          above it, and announcing an empty box would add nothing.
        */}
        <View
          style={styles.reticle}
          pointerEvents="none"
          accessibilityElementsHidden
          importantForAccessibility="no-hide-descendants"
        />

        <View style={styles.bottomBar} pointerEvents="box-none">
          <Pressable
            onPress={() => void openGallery()}
            accessibilityRole="button"
            accessibilityLabel={t('mobile:camera.pickFromGallery')}
            style={({ pressed }) => [styles.iconButton, pressed && { opacity: PRESSED_OPACITY }]}
            testID="camera-gallery"
          >
            <IconUpload size={24} color={colors.surface} />
          </Pressable>

          <Pressable
            onPress={() => void capture()}
            disabled={!ready || capturing}
            accessibilityRole="button"
            accessibilityState={{ disabled: !ready || capturing, busy: capturing }}
            accessibilityLabel={t('mobile:camera.capture')}
            style={({ pressed }) => [
              styles.shutter,
              (!ready || capturing) && styles.shutterDisabled,
              pressed && { opacity: PRESSED_OPACITY },
            ]}
            testID="camera-capture"
          >
            <View style={styles.shutterInner} />
          </Pressable>

          {/* Balances the gallery button so the shutter stays centred. */}
          <View style={styles.iconButton} />
        </View>

        {!ready ? (
          <View style={styles.starting} pointerEvents="none">
            <Text variant="caption" color="inverse" accessibilityLiveRegion="polite">
              {t('mobile:camera.starting')}
            </Text>
          </View>
        ) : null}
      </SafeAreaView>
    </View>
  );
}

function GalleryFallback({ onPress, failed }: { onPress: () => void; failed: boolean }) {
  const { t } = useTranslation(['mobile', 'errors']);

  return (
    <View style={styles.fallback}>
      {failed ? <ErrorState message={t('errors:unexpected')} /> : null}
      <Button
        variant="secondary"
        fullWidth
        leadingIcon={<IconUpload size={20} color={colors.brand600} />}
        onPress={onPress}
        testID="camera-gallery-fallback"
      >
        {t('mobile:camera.pickFromGallery')}
      </Button>
    </View>
  );
}

const styles = StyleSheet.create({
  fill: { flex: 1, backgroundColor: '#000000' },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'space-between',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    padding: spacing.lg,
    backgroundColor: colors.overlay,
  },
  guidance: { flex: 1, gap: 2 },
  reticle: {
    alignSelf: 'center',
    width: '78%',
    aspectRatio: 1,
    borderWidth: 2,
    borderColor: colors.surface,
    borderRadius: radius.lg,
    opacity: 0.7,
  },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    backgroundColor: colors.overlay,
  },
  iconButton: {
    width: TOUCH_TARGET,
    height: TOUCH_TARGET,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutter: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterDisabled: { opacity: 0.5 },
  shutterInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.surface,
  },
  starting: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 120,
    alignItems: 'center',
  },
  previewFrame: {
    width: '100%',
    aspectRatio: 3 / 4,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.canvas,
    overflow: 'hidden',
  },
  previewFill: { width: '100%', height: '100%' },
  fallback: { gap: spacing.md },
});
