#!/usr/bin/env node
/**
 * Creates the local development `.env` files.
 *
 * Three of them, because each app owns its own configuration (ADR-019):
 * `backend/.env`, `ml-service/.env` and `web/frontend/.env`. The values are
 * development-only: the two secrets are generated here with
 * `crypto.randomBytes`, are never printed, and never leave this machine.
 *
 * Guarantees this script makes:
 *
 *   - **It never overwrites.** An existing file is left exactly as it is and
 *     reported as skipped, so re-running after adding a provider key cannot
 *     destroy it. `--force` is deliberately not implemented; delete the file
 *     by hand if you mean it.
 *   - **`SERVICE_KEY` is generated once and written to both** backend and
 *     ml-service. They authenticate to each other with a constant-time compare
 *     of that value, so a mismatch is a 401 on every inference call.
 *   - **No provider keys are invented.** Gemini, OpenRouter, Cloudinary,
 *     OpenWeather and data.gov.in are left commented out. Every one of those
 *     integrations reports its own absence honestly, and a placeholder string
 *     would make an unconfigured provider look configured.
 *
 * Usage:
 *   node scripts/setup-dev-env.mjs
 */
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

const secret = () => randomBytes(32).toString('hex');

/** One key, shared by the two services that have to agree on it. */
const serviceKey = secret();
const jwtSecret = secret();

/**
 * The seeded demo farmer's password, generated rather than fixed.
 *
 * It used to be the literal `demo-farmer-2026`, which meant every clone of this
 * public repository shared one known password for its demo account — and at 16
 * characters it sat under the 20-character threshold on the
 * `generic-secret-assignment` rule in `scan-staged-secrets.mjs`, so the
 * project's own gate could not have caught it. Generated, it is per-machine and
 * long enough that the gate would.
 */
const demoPassword = randomBytes(12).toString('base64url');

/** The local database. No document names one, so it is recorded here. */
const MONGODB_URI = 'mongodb://127.0.0.1:27017/him1096';

const files = [
  {
    target: 'backend/.env',
    contents: `# Local development. Generated by scripts/setup-dev-env.mjs — not committed.
NODE_ENV=development
PORT=4000
LOG_LEVEL=info
CORS_ORIGINS=http://localhost:5173

MONGODB_URI=${MONGODB_URI}

JWT_SECRET=${jwtSecret}
SERVICE_KEY=${serviceKey}

ML_SERVICE_URL=http://127.0.0.1:7860

# Provider credentials are deliberately absent rather than stubbed. Each
# integration reports its own absence, and the crop-health chain degrades to
# the tier below instead of failing (ADR-006). Uncomment and fill to enable:
# GEMINI_API_KEY=
# OPENROUTER_API_KEY=
# OPENWEATHER_API_KEY=
# DATAGOVIN_API_KEY=
# DATAGOVIN_RESOURCE_ID=
# CLOUDINARY_URL=

DISABLE_ML=false
DISABLE_GEMINI=false
DISABLE_OPENROUTER=false

# Seed account for scripts/seed-dev.mjs.
SEED_DEMO_EMAIL=demo@example.com
SEED_DEMO_PASSWORD=${demoPassword}
`,
  },
  {
    target: 'ml-service/.env',
    contents: `# Local development. Generated by scripts/setup-dev-env.mjs — not committed.
# SERVICE_KEY must be byte-identical to the backend's, or every /predict call
# is a 401.
SERVICE_KEY=${serviceKey}
ENV=development
PORT=7860
LOG_LEVEL=INFO

# The trained artefact Phase 4 shipped. Without MODEL_PATH the service falls
# back to StubPredictor, whose outputs carry no visual meaning at all and whose
# model version is prefixed 'stub-' — useful for exercising the HTTP contract,
# useless for looking at a real photograph. Point it at the real model locally.
MODEL_PATH=model/model-v1.0.onnx
`,
  },
  {
    target: 'web/frontend/.env',
    contents: `# Local development. Generated by scripts/setup-dev-env.mjs — not committed.
# Everything VITE_-prefixed is inlined into the client bundle and is world
# readable. There is nothing secret here, and nothing secret may be added.
VITE_API_URL=http://localhost:4000/api/v1
`,
  },
];

let created = 0;
let skipped = 0;

for (const file of files) {
  const absolute = path.join(ROOT, file.target);

  if (existsSync(absolute)) {
    console.log(`skip    ${file.target} (already exists — left untouched)`);
    skipped += 1;
    continue;
  }

  writeFileSync(absolute, file.contents, 'utf8');
  console.log(`create  ${file.target}`);
  created += 1;
}

console.log(`\n${created} created, ${skipped} skipped.`);

if (created > 0) {
  console.log(
    '\nJWT_SECRET and SERVICE_KEY were generated with crypto.randomBytes(32).' +
      '\nThey are development-only and are not printed here by design.' +
      // The demo password is the one generated value a human has to type, so it
      // is the one that gets shown. It unlocks a seeded local account against a
      // local database and nothing else.
      '\n\nThe seeded demo farmer signs in with the password written to' +
      '\nbackend/.env as SEED_DEMO_PASSWORD (generated per machine).',
  );
}

console.log(
  '\nNext:' +
    '\n  1. mongod must be reachable at 127.0.0.1:27017' +
    '\n  2. cd backend && npm run indexes:build && npm run seed:registry' +
    '\n  3. cd backend && npm run seed:dev' +
    '\n  4. cd backend && npm run dev',
);
